/**
 * DreamGraph — engine.env loader.
 *
 * Parses a simple KEY=VALUE env file (no dependencies — no dotenv needed).
 * Supports:
 *   - `KEY=VALUE` and `KEY="VALUE"` and `KEY='VALUE'`
 *   - Comments: lines starting with `#`
 *   - Empty lines are ignored
 *   - Inline comments are NOT supported (values may contain `#`)
 *
 * Values are injected into `process.env` with "instance wins" semantics:
 * if a key is already set in the environment, the engine.env value takes
 * precedence (per-instance config > global env).
 */

import { readFileSync, existsSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { logger } from "./logger.js";

/**
 * Write a set of KEY=VALUE pairs to an engine.env file.
 *
 * Overwrites the entire file.  Adds a header comment and groups
 * values by purpose (base LLM, dreamer, normalizer).
 *
 * @param envPath  Absolute path to the engine.env file.
 * @param vars     Record of env-var names → values to write.  Empty/null
 *                 values are written as commented-out lines.
 */
export function writeEngineEnv(
  envPath: string,
  vars: Record<string, string>,
): void {
  try {
    mkdirSync(dirname(envPath), { recursive: true });

    const template: Array<{ key: string; defaultValue: string; description: string; secret?: boolean }> = [
      {
        key: "DREAMGRAPH_LLM_PROVIDER",
        defaultValue: "ollama",
        description: "LLM provider used for DreamGraph cognitive operations.",
      },
      {
        key: "DREAMGRAPH_LLM_URL",
        defaultValue: "http://localhost:11434",
        description: "Base URL for the configured LLM provider endpoint.",
      },
      {
        key: "DREAMGRAPH_LLM_API_KEY",
        defaultValue: "",
        description: "Optional API key for providers that require authentication. Leave blank to keep unset.",
        secret: true,
      },
      {
        key: "DREAMGRAPH_LLM_DREAMER_MODEL",
        defaultValue: "qwen3:8b",
        description: "Model used for creative dream-cycle generation.",
      },
      {
        key: "DREAMGRAPH_LLM_DREAMER_TEMPERATURE",
        defaultValue: "0.9",
        description: "Sampling temperature for dream generation.",
      },
      {
        key: "DREAMGRAPH_LLM_DREAMER_MAX_TOKENS",
        defaultValue: "4096",
        description: "Maximum output tokens for the dreamer model.",
      },
      {
        key: "DREAMGRAPH_LLM_NORMALIZER_MODEL",
        defaultValue: "qwen3:8b",
        description: "Model used for validation and normalization passes.",
      },
      {
        key: "DREAMGRAPH_LLM_NORMALIZER_TEMPERATURE",
        defaultValue: "0.1",
        description: "Low-temperature setting for consistent normalization.",
      },
      {
        key: "DREAMGRAPH_LLM_NORMALIZER_MAX_TOKENS",
        defaultValue: "1024",
        description: "Maximum output tokens for the normalizer model.",
      },
      {
        key: "DATABASE_URL",
        defaultValue: "postgresql://user:password@host:5432/dbname",
        description: "PostgreSQL connection string used by database schema and query tools.",
        secret: true,
      },
    ];

    const lines: string[] = [
      "# DreamGraph Engine Configuration",
      "# Auto-generated by dashboard config save. Edit freely — values here",
      "# override global environment variables on next daemon restart.",
      "# Unconfigured values are kept as commented placeholders with defaults.",
      "",
    ];

    for (const entry of template) {
      const value = vars[entry.key] ?? "";
      lines.push(`# ${entry.description}`);
      if (value === "" || value == null) {
        const placeholderValue = entry.secret
          ? entry.defaultValue || ""
          : entry.defaultValue;
        lines.push(`# ${entry.key}=${placeholderValue}`);
      } else {
        const needsQuotes = /[\s#"']/.test(value);
        lines.push(`${entry.key}=${needsQuotes ? `"${value}"` : value}`);
      }
      lines.push("");
    }

    const remainingKeys = Object.keys(vars).filter(
      key => !template.some(entry => entry.key === key),
    );
    if (remainingKeys.length > 0) {
      lines.push("# Additional persisted values");
      for (const key of remainingKeys.sort()) {
        const value = vars[key] ?? "";
        if (value === "" || value == null) {
          lines.push(`# ${key}=`);
        } else {
          const needsQuotes = /[\s#"']/.test(value);
          lines.push(`${key}=${needsQuotes ? `"${value}"` : value}`);
        }
      }
      lines.push("");
    }

    writeFileSync(envPath, lines.join("\n"), "utf-8");
    logger.info(`engine.env: persisted ${Object.keys(vars).length} keys to ${envPath}`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.error(`engine.env: failed to write ${envPath}: ${msg}`);
  }
}

/**
 * Load an engine.env file and inject its values into process.env.
 *
 * @param envPath  Absolute path to the engine.env file.
 * @returns        Number of env vars loaded.
 */
export function loadEngineEnv(envPath: string): number {
  if (!existsSync(envPath)) {
    return 0;
  }

  let loaded = 0;

  try {
    const content = readFileSync(envPath, "utf-8");
    const lines = content.split(/\r?\n/);

    for (const raw of lines) {
      const line = raw.trim();

      // Skip empty lines and comments
      if (!line || line.startsWith("#")) continue;

      // Find the first `=`
      const eqIdx = line.indexOf("=");
      if (eqIdx <= 0) continue;

      const key = line.slice(0, eqIdx).trim();
      let value = line.slice(eqIdx + 1).trim();

      // Strip surrounding quotes
      if (
        (value.startsWith('"') && value.endsWith('"')) ||
        (value.startsWith("'") && value.endsWith("'"))
      ) {
        value = value.slice(1, -1);
      }

      // Validate key — must look like an env var name
      if (!/^[A-Z_][A-Z0-9_]*$/i.test(key)) {
        logger.warn(`engine.env: skipping invalid key "${key}"`);
        continue;
      }

      // Instance config OVERRIDES global env (per-instance wins)
      process.env[key] = value;
      loaded++;
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    logger.warn(`engine.env: failed to load ${envPath}: ${msg}`);
  }

  return loaded;
}
